type: intersection
files:
  - "result/bert/spans-pred-original_test.txt"
  - "result/roberta/spans-pred-original_test.txt"
path: "/content/drive/MyDrive/ToxicSpans/results/fixed/bert_base_spans/INTER_CRF_roberta.txt"
