type: intersection
files:
  - "/content/drive/MyDrive/ToxicSpans/results/fixed/bert_base_spans/preds/spans-pred-original_test.txt"
  - "/content/drive/MyDrive/ToxicSpans/results/fixed/bert_base_spans/bert/spans-pred-original_test.txt"
path: "/content/drive/MyDrive/ToxicSpans/results/fixed/bert_base_spans/bert_CRF_LSTM_INTER_SPAN.txt"