type: intersection

files:
  - "result/bert/spans-pred-original_test.txt"
  - "result/spans/spans-pred-original_test.txt"
  - "result/roberta/spans-pred-original_test.txt"
path: "result/combine/INTER_all.txt"
