type: union

files:
  - "/result/roberta/spans-pred-original_test.txt"
  - "/result/spans/spans-pred-original_test.txt"
  - "/result/bert/spans-pred-original_test.txt"
path: "/result/combine/UNION_all.txt"
